const $=id=>document.getElementById(id);
const state={projects:[],active:null,map:null,networkLayer:null,telemetryLayer:null,selected:null,mapMode:'inspect',engMode:'prv'};
const assetKinds={pipe:['pipe','eupipe','main','waterline'],meter:['meter','eumeter','flowmeter'],valve:['valve','gate','prv'],hydrant:['hydrant'],dma:['regionnet','dma','zone','district']};
const colors={pipe:'#5c8da9',meter:'#ffc65c',valve:'#aa82ff',hydrant:'#ff7f6d',dma:'#36a3ff',other:'#72879a'};
function kindFor(name=''){const n=name.toLowerCase();for(const[k,terms]of Object.entries(assetKinds))if(terms.some(t=>n.includes(t)))return k;return'other'}
function initMap(){state.map=L.map('map',{zoomControl:true}).setView([1.35,103.82],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap'}).addTo(state.map);state.networkLayer=L.layerGroup().addTo(state.map);state.telemetryLayer=L.layerGroup().addTo(state.map)}
function openModal(){ $('projectModal').classList.remove('hidden'); }
function closeModal(){ $('projectModal').classList.add('hidden'); }
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function featureCount(project,kind){return project.layers.filter(l=>l.kind===kind).reduce((s,l)=>s+(l.geojson?.features?.length||0),0)}
function pipeLength(project){let m=0;project.layers.filter(l=>l.kind==='pipe').forEach(l=>l.geojson.features.forEach(f=>{const p=f.properties||{};const v=Number(p.LENGTH||p.Length||p.length||p.PIPE_LEN||0);if(Number.isFinite(v))m+=v}));return m}
function updateProjectUI(){const p=state.active;if(!p)return;$('projectTitle').textContent=p.name;$('networkStatus').textContent='GIS loaded';$('projectEmpty').classList.add('hidden');$('projectTree').classList.remove('hidden');const counts={};['pipe','meter','valve','hydrant','dma'].forEach(k=>counts[k]=featureCount(p,k));$('pipeCount').textContent=counts.pipe;$('meterCount').textContent=counts.meter;$('treeMeters').textContent=counts.meter;$('valveCount').textContent=counts.valve;$('hydrantCount').textContent=counts.hydrant;$('dmaCount').textContent=counts.dma||'0';$('treeDmas').textContent=counts.dma;$('assetTotal').textContent=Object.values(counts).reduce((a,b)=>a+b,0);const km=pipeLength(p)/1000;$('pipeLength').textContent=km?km.toFixed(1)+' km':counts.pipe+' seg';$('flowCount').textContent=p.telemetry.filter(x=>x.type==='flow').length;$('pressureCount').textContent=p.telemetry.filter(x=>x.type==='pressure').length;$('acousticCount').textContent=p.telemetry.filter(x=>x.type==='acoustic').length;$('telemetryCount').textContent=p.telemetry.length;$('pressureStatus').textContent=p.telemetry.some(x=>x.type==='pressure')?'Connected':'No stream';$('acousticStatus').textContent=p.telemetry.some(x=>x.type==='acoustic')?'Connected':'No stream';$('confidence').textContent=confidenceScore(p)+'%';renderHealth();renderEvents()}
function confidenceScore(p){let s=35;if(featureCount(p,'pipe'))s+=20;if(featureCount(p,'meter'))s+=10;if(featureCount(p,'valve'))s+=8;if(featureCount(p,'dma'))s+=7;if(p.telemetry.some(x=>x.type==='flow'))s+=8;if(p.telemetry.some(x=>x.type==='pressure'))s+=7;if(p.telemetry.some(x=>x.type==='acoustic'))s+=5;return Math.min(100,s)}
function normalizeShpResult(raw){if(!raw)return[];if(raw.type==='FeatureCollection')return[{name:'network',geojson:raw}];if(Array.isArray(raw))return raw.map((g,i)=>({name:g.fileName||g.name||('layer_'+(i+1)),geojson:g}));return Object.entries(raw).filter(([,g])=>g&&g.type==='FeatureCollection').map(([name,geojson])=>({name,geojson}))}
function renderProject(){const p=state.active;if(!p)return;state.networkLayer.clearLayers();let bounds=[];p.layers.forEach(layer=>{const kind=layer.kind;const gj=L.geoJSON(layer.geojson,{style:()=>({color:colors[kind]||colors.other,weight:kind==='pipe'?3:2,fillColor:colors[kind]||colors.other,fillOpacity:kind==='dma'?.05:.18}),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:kind==='meter'?4:kind==='valve'?5:4,color:colors[kind]||colors.other,fillColor:colors[kind]||colors.other,fillOpacity:.9,weight:1}),onEachFeature:(f,l)=>{l.on('click',()=>selectFeature(layer,f,l));}});gj.addTo(state.networkLayer);try{const b=gj.getBounds();if(b.isValid())bounds.push(b)}catch(e){}});if(bounds.length){let b=bounds[0];for(let i=1;i<bounds.length;i++)b=b.extend(bounds[i]);state.map.fitBounds(b.pad(.06))}updateProjectUI()}
function selectFeature(layer,f,l){state.selected={layer,feature:f,leaflet:l};const p=f.properties||{};const rows=Object.entries(p).slice(0,6).map(([k,v])=>k+': '+v).join(' · ');$('selectionCard').innerHTML='<small>SELECTION</small><b>'+escapeHtml(layer.name)+' · '+escapeHtml(layer.kind)+'</b><p>'+escapeHtml(rows||'No attributes')+'</p>'}
async function createProject(){const file=$('gisInput').files[0];if(!file){alert('Choose a zipped shapefile or GeoJSON package.');return}const name=$('projectName').value.trim()||file.name.replace(/\.(zip|json|geojson)$/i,'');$('createProjectBtn').textContent='Reading GIS…';$('createProjectBtn').disabled=true;try{let raw;if(/\.zip$/i.test(file.name)){const buf=await file.arrayBuffer();raw=await shp(buf)}else{raw=JSON.parse(await file.text())}const layers=normalizeShpResult(raw).map(x=>({...x,kind:kindFor(x.name)}));const project={id:'p_'+Date.now(),name,utility:$('utilityName').value.trim(),source:file.name,layers,telemetry:[],created:new Date().toISOString()};state.projects.push(project);state.active=project;const o=document.createElement('option');o.value=project.id;o.textContent=project.name;$('projectSelect').appendChild(o);$('projectSelect').value=project.id;closeModal();renderProject();addAi('Project <b>'+escapeHtml(project.name)+'</b> opened. I classified '+layers.length+' GIS layers and '+layers.reduce((s,l)=>s+l.geojson.features.length,0)+' features. You can now import flow, pressure, meter or acoustic telemetry.')}catch(e){console.error(e);alert('GIS import failed: '+e.message)}finally{$('createProjectBtn').textContent='Create & analyse project';$('createProjectBtn').disabled=false}}
function parseCSV(text){const lines=text.trim().split(/\r?\n/);if(lines.length<2)return[];const h=lines[0].split(',').map(x=>x.trim());return lines.slice(1).map(line=>{const cols=line.split(',');return Object.fromEntries(h.map((k,i)=>[k,cols[i]?.trim()]))})}
function inferTelemetry(row){const keys=Object.keys(row).map(k=>k.toLowerCase());const has=s=>keys.some(k=>k.includes(s));return has('acoustic')||has('noise')?'acoustic':has('pressure')?'pressure':has('flow')||has('mnf')?'flow':has('meter')||has('consumption')?'meter':'other'}
async function importTelemetry(file){if(!state.active){alert('Open a project first.');return}const rows=/\.json$/i.test(file.name)?JSON.parse(await file.text()):parseCSV(await file.text());const arr=Array.isArray(rows)?rows:(rows.records||[]);arr.forEach((r,i)=>state.active.telemetry.push({...r,_id:r.id||('T'+(i+1)),type:r.type||inferTelemetry(r)}));renderTelemetry();updateProjectUI();addAi('Imported <b>'+arr.length+'</b> telemetry records. I can now combine them with the GIS when answering network questions.')}
function renderTelemetry(){state.telemetryLayer.clearLayers();if(!state.active)return;state.active.telemetry.forEach(t=>{const lat=Number(t.lat||t.latitude),lng=Number(t.lng||t.lon||t.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;const c=t.type==='pressure'?colors.dma:t.type==='acoustic'?colors.hydrant:colors.meter;L.circleMarker([lat,lng],{radius:5,color:c,fillColor:c,fillOpacity:1}).bindTooltip((t._id||'Telemetry')+' · '+t.type).addTo(state.telemetryLayer)})}
function renderHealth(){const p=state.active;if(!p)return;const vals=[['GIS topology',featureCount(p,'pipe')?'Ready':'Missing'],['Flow / meter',p.telemetry.some(x=>['flow','meter'].includes(x.type))?'Ready':'Missing'],['Pressure',p.telemetry.some(x=>x.type==='pressure')?'Ready':'Missing'],['Acoustic',p.telemetry.some(x=>x.type==='acoustic')?'Ready':'Missing']];$('dataHealth').innerHTML=vals.map(([a,b])=>'<div><span>'+a+'</span><b>'+b+'</b></div>').join('')}
function renderEvents(){const p=state.active;if(!p)return;const events=[];const pipes=featureCount(p,'pipe'),meters=featureCount(p,'meter'),dmas=featureCount(p,'dma');if(pipes&&!dmas)events.push({sev:'med',title:'DMA boundaries not confirmed',body:'Network contains '+pipes+' pipe features but no recognized DMA/region layer.',tag:'DMA design'});if(pipes&&!meters)events.push({sev:'med',title:'Meter coverage unavailable',body:'Aqua cannot complete a defensible water balance until inlet/customer meter data is mapped.',tag:'Data gap'});if(!p.telemetry.length)events.push({sev:'low',title:'No live operational evidence',body:'Import flow, pressure or acoustic telemetry to move from GIS planning to event detection.',tag:'Telemetry'});if(p.telemetry.some(x=>x.type==='flow')&&!p.telemetry.some(x=>x.type==='pressure'))events.push({sev:'med',title:'Flow present without pressure context',body:'Pressure logging will improve leakage interpretation and pressure-management advice.',tag:'Pressure'});if(!events.length)events.push({sev:'low',title:'Network ready for analysis',body:'GIS and operational evidence are available. Run water balance, DMA planning or acoustic deployment.',tag:'Ready'});$('eventList').innerHTML=events.map(e=>'<div class="event '+e.sev+'"><i></i><div><b>'+e.title+'</b><p>'+e.body+'</p></div><strong>'+e.tag+'</strong></div>').join('')}
function addAi(html){const d=document.createElement('div');d.className='msg ai';d.innerHTML='<b>Aqua</b><p>'+html+'</p>';$('chat').appendChild(d);$('chat').scrollTop=$('chat').scrollHeight}
function addUser(text){const d=document.createElement('div');d.className='msg user';d.innerHTML='<b>You</b><p>'+escapeHtml(text)+'</p>';$('chat').appendChild(d);$('chat').scrollTop=$('chat').scrollHeight}
function contextSnapshot(){const p=state.active;if(!p)return null;return{project:p.name,utility:p.utility,layers:p.layers.map(l=>({name:l.name,kind:l.kind,count:l.geojson.features.length})),telemetry:p.telemetry.slice(-250),selected:state.selected?{layer:state.selected.layer.name,kind:state.selected.layer.kind,properties:state.selected.feature.properties}:null,confidence:confidenceScore(p)}}
async function askCopilot(q){addUser(q);if(!state.active){addAi('Open a project first. The Copilot needs the network context before it can reason about NRW.');return}addAi('<span class="thinking">Analysing network context…</span>');const nodes=[...$('chat').querySelectorAll('.msg.ai')];const placeholder=nodes[nodes.length-1];try{const res=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,context:contextSnapshot()})});if(!res.ok)throw new Error('Copilot service unavailable');const data=await res.json();placeholder.innerHTML='<b>Aqua</b><p>'+escapeHtml(data.answer||'No answer returned.')+'</p>'}catch(e){placeholder.innerHTML='<b>Aqua</b><p>'+localReasoning(q)+'</p>'}}
function localReasoning(q){const p=state.active;const c={pipe:featureCount(p,'pipe'),meter:featureCount(p,'meter'),valve:featureCount(p,'valve'),dma:featureCount(p,'dma')};const flows=p.telemetry.filter(x=>x.type==='flow'),press=p.telemetry.filter(x=>x.type==='pressure'),ac=p.telemetry.filter(x=>x.type==='acoustic');return 'The LLM service is not connected in this prototype, so I will not pretend to produce a neural-language diagnosis. Current evidence: <b>'+c.pipe+'</b> pipes, <b>'+c.meter+'</b> meters, <b>'+c.valve+'</b> valves, <b>'+c.dma+'</b> DMA/region features, '+flows.length+' flow records, '+press.length+' pressure records and '+ac.length+' acoustic records. Connect the Copilot API to enable full natural-language tool-calling analysis.'}
function runWaterBalance(){if(!state.active)return;const flow=state.active.telemetry.filter(x=>x.type==='flow'),meters=state.active.telemetry.filter(x=>x.type==='meter');addAi(flow.length&&meters.length?'Water-balance inputs are present. The next engine step is to aggregate system input volume, authorized consumption and apparent/real losses by DMA and time window.':'A defensible water balance needs both system input/flow data and customer or authorized-consumption meter data. Import those streams and I will calculate it by DMA.')}
function runDmaPlanner(){if(!state.active)return;const d=featureCount(state.active,'dma'),v=featureCount(state.active,'valve'),m=featureCount(state.active,'meter');addAi(d?'I found '+d+' DMA/region features. I would validate boundary connectivity against '+v+' valves and '+m+' meter assets, then score candidate boundary changes.':'No recognized DMA/region layer was found. Use Draw DMA or import a regionnet/DMA layer; then Aqua can validate boundary valves and inlet-meter coverage.')}
function runSensorPlanner(){if(!state.active)return;const pipes=featureCount(state.active,'pipe');addAi('Acoustic deployment planner is ready to score '+pipes+' pipe features using material/diameter attributes, access points, pressure, burst history and acoustic evidence. Once sensor inventory is connected, it can produce nightly lift-and-shift routes or permanent coverage.')}
function engineeringAnalysis(){if(!state.active)return;const s=state.selected;if(!s){$('engineeringBody').innerHTML='<p>Select a pipe or candidate location first.</p><button class="secondary" id="runEngineering">Analyse selected location</button>';bindEngineering();return}const p=s.feature.properties||{};const dia=p.DIAMETER||p.DIA||p.SIZE||p.size||'unknown';if(state.engMode==='prv')$('engineeringBody').innerHTML='<p><b>Preliminary PRV review</b></p><p>Selected '+escapeHtml(s.layer.kind)+'; indicated diameter: <b>'+escapeHtml(dia)+'</b>. Aqua should evaluate upstream/downstream pressure envelopes, minimum/peak flow, elevation, fire-flow constraints and valve authority before sizing. This location is a candidate only until those inputs are available.</p><button class="secondary" id="runEngineering">Re-run analysis</button>';else $('engineeringBody').innerHTML='<p><b>Preliminary air-valve review</b></p><p>Selected '+escapeHtml(s.layer.kind)+'; indicated diameter: <b>'+escapeHtml(dia)+'</b>. Aqua should use the longitudinal profile to locate summits and slope changes, then calculate air-release and vacuum-admission requirements for filling, draining and transient conditions.</p><button class="secondary" id="runEngineering">Re-run analysis</button>';bindEngineering()}
function bindEngineering(){const b=$('runEngineering');if(b)b.onclick=engineeringAnalysis}
function bind(){['newProjectBtn','emptyNewProject'].forEach(id=>$(id).onclick=openModal);$('closeProject').onclick=closeModal;$('gisDrop').onclick=()=>$('gisInput').click();$('gisInput').onchange=e=>$('gisFileName').textContent=e.target.files[0]?.name||'No GIS file selected';$('createProjectBtn').onclick=createProject;$('projectSelect').onchange=e=>{state.active=state.projects.find(p=>p.id===e.target.value)||null;if(state.active){renderProject();renderTelemetry()}};$('importTelemetryBtn').onclick=()=>$('telemetryInput').click();$('telemetryInput').onchange=e=>e.target.files[0]&&importTelemetry(e.target.files[0]);$('askBtn').onclick=()=>{const q=$('prompt').value.trim();if(q){$('prompt').value='';askCopilot(q)}};$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('askBtn').click()}});document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>askCopilot(b.textContent));$('runWaterBalance').onclick=runWaterBalance;$('runDmaPlanner').onclick=runDmaPlanner;$('runSensorPlanner').onclick=runSensorPlanner;$('refreshEvents').onclick=renderEvents;document.querySelectorAll('.eng-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.eng-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.engMode=b.dataset.eng;engineeringAnalysis()});document.querySelectorAll('[data-map-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-map-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mapMode=b.dataset.mapMode});bindEngineering()}
window.addEventListener('load',()=>{initMap();bind()});